// <auto-generated />
using DigimonAPI.entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250121035123_StatsClassandRelations")]
    partial class StatsClassandRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArtifactSpawn", b =>
                {
                    b.Property<int>("ArtifactId")
                        .HasColumnType("integer");

                    b.Property<int>("SpawnArtifactId")
                        .HasColumnType("integer");

                    b.HasKey("ArtifactId", "SpawnArtifactId");

                    b.HasIndex("SpawnArtifactId");

                    b.ToTable("ArtifactSpawn");
                });

            modelBuilder.Entity("ArtifactsContents", b =>
                {
                    b.Property<int>("ContentId")
                        .HasColumnType("integer");

                    b.Property<int>("SpawnId")
                        .HasColumnType("integer");

                    b.HasKey("ContentId", "SpawnId");

                    b.HasIndex("SpawnId");

                    b.ToTable("ArtifactsContents");
                });

            modelBuilder.Entity("DigimonAPI.entities.Artifact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Artifacts");
                });

            modelBuilder.Entity("DigimonAPI.entities.Attribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("StrongId")
                        .HasColumnType("integer");

                    b.Property<int?>("WeakId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StrongId");

                    b.HasIndex("WeakId");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("DigimonAPI.entities.ContentArtifacts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("ContentArtifacts");
                });

            modelBuilder.Entity("DigimonAPI.entities.ContentDigimons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("ContentDigimons");
                });

            modelBuilder.Entity("DigimonAPI.entities.ContentEvents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("ContentEvents");
                });

            modelBuilder.Entity("DigimonAPI.entities.ContentUsables", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("ContentUsables");
                });

            modelBuilder.Entity("DigimonAPI.entities.Digimon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttributeId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("TierId")
                        .HasColumnType("integer");

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.HasIndex("ImgUrl")
                        .IsUnique();

                    b.HasIndex("TierId");

                    b.HasIndex("TypeId");

                    b.ToTable("Digimons");
                });

            modelBuilder.Entity("DigimonAPI.entities.Dungeon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtifactsContentId")
                        .HasColumnType("integer");

                    b.Property<string>("BattleImgUrl")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DigimonsContentId")
                        .HasColumnType("integer");

                    b.Property<int>("EventsContentId")
                        .HasColumnType("integer");

                    b.Property<string>("ExploreImgUrl")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UsablesContentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactsContentId");

                    b.HasIndex("DigimonsContentId");

                    b.HasIndex("EventsContentId");

                    b.HasIndex("UsablesContentId");

                    b.ToTable("Dungeon");
                });

            modelBuilder.Entity("DigimonAPI.entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("DigimonAPI.entities.SpawnArtifact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Chance")
                        .HasColumnType("integer");

                    b.Property<string>("CollectionType")
                        .HasColumnType("text");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SpawnArtifacts");
                });

            modelBuilder.Entity("DigimonAPI.entities.SpawnDigimon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Chance")
                        .HasColumnType("integer");

                    b.Property<string>("CollectionType")
                        .HasColumnType("text");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SpawnDigimons");
                });

            modelBuilder.Entity("DigimonAPI.entities.SpawnEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Chance")
                        .HasColumnType("integer");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SpawnEvents");
                });

            modelBuilder.Entity("DigimonAPI.entities.SpawnUsable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Chance")
                        .HasColumnType("integer");

                    b.Property<string>("CollectionType")
                        .HasColumnType("text");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SpawnUsables");
                });

            modelBuilder.Entity("DigimonAPI.entities.SpecialMove", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("SpecialMoves");
                });

            modelBuilder.Entity("DigimonAPI.entities.Stats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArtifactId")
                        .HasColumnType("integer");

                    b.Property<string>("Association")
                        .HasColumnType("text");

                    b.Property<int>("Cha")
                        .HasColumnType("integer");

                    b.Property<int?>("DigimonId")
                        .HasColumnType("integer");

                    b.Property<int>("Mhp")
                        .HasColumnType("integer");

                    b.Property<int>("Pow")
                        .HasColumnType("integer");

                    b.Property<int>("Res")
                        .HasColumnType("integer");

                    b.Property<int>("Spd")
                        .HasColumnType("integer");

                    b.Property<int>("Sta")
                        .HasColumnType("integer");

                    b.Property<int>("Will")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("DigimonId");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("DigimonAPI.entities.Tier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Tiers");
                });

            modelBuilder.Entity("DigimonAPI.entities.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("DigimonAPI.entities.Usable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Usables");
                });

            modelBuilder.Entity("DigimonSpawn", b =>
                {
                    b.Property<int>("DigimonId")
                        .HasColumnType("integer");

                    b.Property<int>("SpawnDigimonId")
                        .HasColumnType("integer");

                    b.HasKey("DigimonId", "SpawnDigimonId");

                    b.HasIndex("SpawnDigimonId");

                    b.ToTable("DigimonSpawn");
                });

            modelBuilder.Entity("DigimonSpecialMove", b =>
                {
                    b.Property<int>("DigimonId")
                        .HasColumnType("integer");

                    b.Property<int>("SpecialMoveId")
                        .HasColumnType("integer");

                    b.HasKey("DigimonId", "SpecialMoveId");

                    b.HasIndex("SpecialMoveId");

                    b.ToTable("DigimonSpecialMove");
                });

            modelBuilder.Entity("DigimonsContents", b =>
                {
                    b.Property<int>("ContentId")
                        .HasColumnType("integer");

                    b.Property<int>("SpawnId")
                        .HasColumnType("integer");

                    b.HasKey("ContentId", "SpawnId");

                    b.HasIndex("SpawnId");

                    b.ToTable("DigimonsContents");
                });

            modelBuilder.Entity("EventSpawn", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("SpawnEventId")
                        .HasColumnType("integer");

                    b.HasKey("EventId", "SpawnEventId");

                    b.HasIndex("SpawnEventId");

                    b.ToTable("EventSpawn");
                });

            modelBuilder.Entity("EventsContents", b =>
                {
                    b.Property<int>("ContentId")
                        .HasColumnType("integer");

                    b.Property<int>("SpawnId")
                        .HasColumnType("integer");

                    b.HasKey("ContentId", "SpawnId");

                    b.HasIndex("SpawnId");

                    b.ToTable("EventsContents");
                });

            modelBuilder.Entity("UsableSpawn", b =>
                {
                    b.Property<int>("SpawnUsableId")
                        .HasColumnType("integer");

                    b.Property<int>("UsableId")
                        .HasColumnType("integer");

                    b.HasKey("SpawnUsableId", "UsableId");

                    b.HasIndex("UsableId");

                    b.ToTable("UsableSpawn");
                });

            modelBuilder.Entity("UsablesContents", b =>
                {
                    b.Property<int>("ContentId")
                        .HasColumnType("integer");

                    b.Property<int>("SpawnId")
                        .HasColumnType("integer");

                    b.HasKey("ContentId", "SpawnId");

                    b.HasIndex("SpawnId");

                    b.ToTable("UsablesContents");
                });

            modelBuilder.Entity("ArtifactSpawn", b =>
                {
                    b.HasOne("DigimonAPI.entities.Artifact", null)
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigimonAPI.entities.SpawnArtifact", null)
                        .WithMany()
                        .HasForeignKey("SpawnArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtifactsContents", b =>
                {
                    b.HasOne("DigimonAPI.entities.ContentArtifacts", null)
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigimonAPI.entities.SpawnArtifact", null)
                        .WithMany()
                        .HasForeignKey("SpawnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DigimonAPI.entities.Attribute", b =>
                {
                    b.HasOne("DigimonAPI.entities.Attribute", "StrongAgainst")
                        .WithMany()
                        .HasForeignKey("StrongId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DigimonAPI.entities.Attribute", "WeakAgainst")
                        .WithMany()
                        .HasForeignKey("WeakId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("StrongAgainst");

                    b.Navigation("WeakAgainst");
                });

            modelBuilder.Entity("DigimonAPI.entities.Digimon", b =>
                {
                    b.HasOne("DigimonAPI.entities.Attribute", "Attribute")
                        .WithMany("Digimons")
                        .HasForeignKey("AttributeId");

                    b.HasOne("DigimonAPI.entities.Tier", "Tier")
                        .WithMany("Digimons")
                        .HasForeignKey("TierId");

                    b.HasOne("DigimonAPI.entities.Type", "Type")
                        .WithMany("Digimons")
                        .HasForeignKey("TypeId");

                    b.Navigation("Attribute");

                    b.Navigation("Tier");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("DigimonAPI.entities.Dungeon", b =>
                {
                    b.HasOne("DigimonAPI.entities.ContentArtifacts", "Artifacts")
                        .WithMany("Dungeons")
                        .HasForeignKey("ArtifactsContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigimonAPI.entities.ContentDigimons", "Digimons")
                        .WithMany("Dungeons")
                        .HasForeignKey("DigimonsContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigimonAPI.entities.ContentEvents", "Events")
                        .WithMany("Dungeons")
                        .HasForeignKey("EventsContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigimonAPI.entities.ContentUsables", "Usables")
                        .WithMany("Dungeons")
                        .HasForeignKey("UsablesContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifacts");

                    b.Navigation("Digimons");

                    b.Navigation("Events");

                    b.Navigation("Usables");
                });

            modelBuilder.Entity("DigimonAPI.entities.Stats", b =>
                {
                    b.HasOne("DigimonAPI.entities.Artifact", "Artifact")
                        .WithMany("Stats")
                        .HasForeignKey("ArtifactId");

                    b.HasOne("DigimonAPI.entities.Digimon", "Digimon")
                        .WithMany("Stats")
                        .HasForeignKey("DigimonId");

                    b.Navigation("Artifact");

                    b.Navigation("Digimon");
                });

            modelBuilder.Entity("DigimonSpawn", b =>
                {
                    b.HasOne("DigimonAPI.entities.Digimon", null)
                        .WithMany()
                        .HasForeignKey("DigimonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigimonAPI.entities.SpawnDigimon", null)
                        .WithMany()
                        .HasForeignKey("SpawnDigimonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DigimonSpecialMove", b =>
                {
                    b.HasOne("DigimonAPI.entities.Digimon", null)
                        .WithMany()
                        .HasForeignKey("DigimonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigimonAPI.entities.SpecialMove", null)
                        .WithMany()
                        .HasForeignKey("SpecialMoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DigimonsContents", b =>
                {
                    b.HasOne("DigimonAPI.entities.ContentDigimons", null)
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigimonAPI.entities.SpawnDigimon", null)
                        .WithMany()
                        .HasForeignKey("SpawnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventSpawn", b =>
                {
                    b.HasOne("DigimonAPI.entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigimonAPI.entities.SpawnEvent", null)
                        .WithMany()
                        .HasForeignKey("SpawnEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventsContents", b =>
                {
                    b.HasOne("DigimonAPI.entities.ContentEvents", null)
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigimonAPI.entities.SpawnEvent", null)
                        .WithMany()
                        .HasForeignKey("SpawnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UsableSpawn", b =>
                {
                    b.HasOne("DigimonAPI.entities.SpawnUsable", null)
                        .WithMany()
                        .HasForeignKey("SpawnUsableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigimonAPI.entities.Usable", null)
                        .WithMany()
                        .HasForeignKey("UsableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UsablesContents", b =>
                {
                    b.HasOne("DigimonAPI.entities.ContentUsables", null)
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigimonAPI.entities.SpawnUsable", null)
                        .WithMany()
                        .HasForeignKey("SpawnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DigimonAPI.entities.Artifact", b =>
                {
                    b.Navigation("Stats");
                });

            modelBuilder.Entity("DigimonAPI.entities.Attribute", b =>
                {
                    b.Navigation("Digimons");
                });

            modelBuilder.Entity("DigimonAPI.entities.ContentArtifacts", b =>
                {
                    b.Navigation("Dungeons");
                });

            modelBuilder.Entity("DigimonAPI.entities.ContentDigimons", b =>
                {
                    b.Navigation("Dungeons");
                });

            modelBuilder.Entity("DigimonAPI.entities.ContentEvents", b =>
                {
                    b.Navigation("Dungeons");
                });

            modelBuilder.Entity("DigimonAPI.entities.ContentUsables", b =>
                {
                    b.Navigation("Dungeons");
                });

            modelBuilder.Entity("DigimonAPI.entities.Digimon", b =>
                {
                    b.Navigation("Stats");
                });

            modelBuilder.Entity("DigimonAPI.entities.Tier", b =>
                {
                    b.Navigation("Digimons");
                });

            modelBuilder.Entity("DigimonAPI.entities.Type", b =>
                {
                    b.Navigation("Digimons");
                });
#pragma warning restore 612, 618
        }
    }
}
